name: build-xs-galactic

on:
  push:
    branches:
      - galactic
      - ros2-devel
  pull_request:
    branches:
      - galactic
      - ros2-devel
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  xs-galactic:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: galactic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ROS Toolboxes
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: src/interbotix_ros_toolboxes
      - name: Checkout ROS Core
        uses: actions/checkout@v2
        with:
          repository: interbotix/interbotix_ros_core
          ref: galactic
          submodules: recursive
          path: src/interbotix_ros_core
      - name: ROS-I CI
        uses: ros-industrial/industrial_ci@master
        with:
          config: ${{toJSON(matrix.env)}}
